export const LOAD_USERS_START   = 'LOAD_USERS_START'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAILED  = 'LOAD_USERS_FAILED'

export const ADD_DEPOSIT_START   = 'ADD_DEPOSIT_START'
export const ADD_DEPOSIT_SUCCESS = 'ADD_DEPOSIT_SUCCESS'
export const ADD_DEPOSIT_FAILED  = 'ADD_DEPOSIT_FAILED'